### ISSUE TITLE
NullPointerException when component schema contains enum property with enum value of null

### ISSUE THREAD

**Issue by tmack8001** [swagger-api/swagger-codegen-generators#693] opened 2020-06-04 02:31 UTC
Example snippet from a completely valid swagger after https://github.com/swagger-api/swagger-parser/issues/1008 was added to allow enum types to have a value of `null`.

```yaml
schemas:
    MyRequestSchema:
      type: object
      required:
        - id
      properties:
        id:
          type: string
          description: Object identifier
        type:
          type: string
          nullable: true
          enum:
            - SMALL
            - MEDIUM
            - LARGE
            - null
          description: type of the request object
```

However when using this type of component structure I'm getting the following error on v3.0.20.

```
Exception in thread "Thread-0" java.lang.RuntimeException: Could not process model 'MyRequestSchema'.Please make sure that your schema is correct!
	at io.swagger.codegen.v3.DefaultGenerator.generateModels(DefaultGenerator.java:404)
	at io.swagger.codegen.v3.DefaultGenerator.generate(DefaultGenerator.java:783)
	at io.swagger.codegen.v3.cli.cmd.Generate.run(Generate.java:351)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.NullPointerException
	at io.swagger.codegen.v3.generators.DefaultCodegenConfig.findEnumName(DefaultCodegenConfig.java:340)
	at io.swagger.codegen.v3.generators.DefaultCodegenConfig.updateCodegenPropertyEnum(DefaultCodegenConfig.java:3782)
	at io.swagger.codegen.v3.generators.DefaultCodegenConfig.processModelEnums(DefaultCodegenConfig.java:332)
	at io.swagger.codegen.v3.generators.DefaultCodegenConfig.postProcessModelsEnum(DefaultCodegenConfig.java:301)
	at io.swagger.codegen.v3.generators.python.PythonClientCodegen.postProcessModels(PythonClientCodegen.java:276)
	at io.swagger.codegen.v3.DefaultGenerator.processModels(DefaultGenerator.java:1054)
	at io.swagger.codegen.v3.DefaultGenerator.generateModels(DefaultGenerator.java:375)
	... 3 more
```

**Comment by tmack8001** [comment] 2020-06-04 02:31
When I simply remove the `null` enum value the generator creates in my case the `python` client successfully.

**Comment by HugoMario** [comment] 2020-06-30 23:26
hello @tmack8001, i tried to reproduce this locally but it works fine, can you try with [swagger-codegen-cli_SNAPSHOT-3.0.21.jar](https://oss.sonatype.org/content/repositories/snapshots/io/swagger/codegen/v3/swagger-codegen-cli/3.0.21-SNAPSHOT/swagger-codegen-cli-3.0.21-20200630.212712-47.jar) and check if the issue is still present ?

going to close it for now, but if you still got the issue i'll reopen it and work on it asap

**Closed by HugoMario** 2020-06-30 23:26 UTC

**Comment by tmack8001** [comment] 2020-07-02 17:54
I will take a look and see if I can reproduce this.
